# Generated by Django 2.1.1 on 2018-09-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, verbose_name='Score'),
        ),
    ]
