# Generated by Django 2.1.1 on 2018-09-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180915_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Email'),
        ),
    ]
