# Generated by Django 2.1.1 on 2018-09-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180916_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='bio',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='blog',
            field=models.CharField(blank=True, max_length=255, verbose_name='Blog'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='followers',
            field=models.IntegerField(null=True, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='following',
            field=models.IntegerField(null=True, verbose_name='Following'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='hireable',
            field=models.BooleanField(default=False, verbose_name='Hireable'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='public_gists',
            field=models.CharField(blank=True, max_length=255, verbose_name='Public Gist'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='public_repos',
            field=models.CharField(blank=True, max_length=255, verbose_name='Public Gist'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created At'),
        ),
    ]
