# Generated by Django 2.1.1 on 2018-09-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180916_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='blog',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='events_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Events URL'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='gists_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gists URL'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='gravatar_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gravatar ID'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='html_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Html URL'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='organizations_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organizations URL'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='public_gists',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public Gist'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='public_repos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public Gist'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='received_events_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Received events URL'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='repos_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Repos URL'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='starred_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Starred URL'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='subscriptions_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subscriptions URL'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
