# Generated by Django 2.1.1 on 2018-09-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180916_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='hireable',
            field=models.BooleanField(default=False, null=True, verbose_name='Hireable'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='site_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='Siteadmin'),
        ),
    ]
